### ISSUE TITLE
Allow use behind a proxy

### ISSUE THREAD

**Issue by jreichenberg** [juliangruber/download-chromium#4]
Thanks for doing this... the approach works really well. One thing that would help: On https://github.com/juliangruber/download-chromium/blob/master/index.js#L17 you call https.get() using the string url as the first arg.  This was causing connect timeouts for me as I'm behind a corporate proxy. I think if you updated to the following it would handle this case transparently:

```
const get = url => new Promise(resolve => https.get({url: url, proxy: process.env.HTTPS_PROXY}, resolve))
```

As it stands, I needed to do the following workaround:

```
function fetchChromium(opts) {
  // monkey-patch https to accomodate proxies
  const https = require('https');
  const oldGet = https.get;
  https.get = (opts, cb) => {
    if (typeof opts === 'string') {
      opts = {url: opts};
    }
    opts.proxy = process.env.HTTPS_PROXY;
    oldGet(opts, cb);
  }

  //do download if needed + reset monkey-patch of https get
  return require('download-chromium')({ log: true, revision: '558114' })
    .then(localPath => {
      https.get = oldGet;
      return Promise.resolve({localPath: localPath});
    })
    .catch(err => {
      return Promise.reject(err);
    });
}
```

**Comment by jreichenberg** [comment]
... a pre-step to the proxy solution is done by the puppeteer project, which also downloads chromium...  Sets the proxy settings environment vars by looking for them inside npm config like this: https://github.com/GoogleChrome/puppeteer/blob/master/install.js#L42

**Comment by juliangruber** [comment]
#5

**Comment by juliangruber** [comment]
Thanks for figuring this out :)

**Comment by jreichenberg** [comment]
Thanks.  I'm actually getting inconsistent results now and can't vouch for the update right now.  I'll try again today, but the bad news is I'm also noticing that puppeteer does some more things involving https-proxy-agent and other things... may not be as simple as I proposed.
