### ISSUE TITLE
After Chromium r591479 win filename changed

### ISSUE THREAD

**Issue by Johann-S** [juliangruber/download-chromium#7]
Hi @juliangruber,

Thanks for your tool 👍 

After Chromium r591479 the Windows filename change according to: https://github.com/GoogleChrome/puppeteer/blob/v1.15.0/lib/BrowserFetcher.js#L52

Do you plan to fix that ?

**Comment by juliangruber** [comment]
Hey, thanks for the notice! Could you create a pull request for this? :)
