### ISSUE TITLE
Connection error since 2.1.0

### ISSUE THREAD

**Issue by dspnorman** [juliangruber/download-chromium#9]
Hello @juliangruber, and thank you for this great tool!

I just noticed one of my CI builds (which uses `download-chromium`) started failing, and it appears related to `2.1.0`. Here's the error I see logged, which I can reproduce by simply installing locally on my Mac and running the command with no arguments (in CI I am targeting latest stable, 638880, but the behavior is the same):

```
$ download-chromium
Downloading Chromium r499413...events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
```

If I pin to `2.0.2` things work as expected, and my CI build runs and passes.

Thanks very much for taking a look into this.

**Comment by GreenGremlin** [comment]
This appears to be related to [this change](https://github.com/juliangruber/download-chromium/pull/5/files). The change is taking advantage the `https.get(url[, options][, callback])` signature that was [added in node](https://github.com/nodejs/node/commit/19aa41c6fc92408fa078d3a10d780a599f7bca01) v10.9.0.

**Comment by GreenGremlin** [comment]
This looks to be a regression of https://github.com/juliangruber/download-chromium/pull/5. The change updates the call to `https.get` to pass options as `{url, proxy}`. From what I can tell neither `url` nor `proxy` are a valid option for `https.get`.

**Comment by juliangruber** [comment]
I'm very sorry about this! I've now added CI and fixed this condition. Find the patch in v2.1.1

**Comment by GreenGremlin** [comment]
Thank you for the quick response! And for adding CI!

**Comment by dspnorman** [comment]
Thanks very much! I just verified the patch is working for my use case.
